# Immutable upstream input; Dependabot updates the tag and digest in PRs.
FROM registry-1.docker.io/library/golang:1.27.1-alpine3.24@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS upstream
#!DisableOBSContainerSupport
WORKDIR /src
COPY src/ /src/
ADD vendor.tar.gz /src/
RUN CGO_ENABLED=0 GOPROXY=off GOSUMDB=off go build -mod=vendor -trimpath -ldflags="-s -w" -o /certspotter software.sslmate.com/src/certspotter/cmd/certspotter
FROM scratch
COPY --from=upstream /certspotter /usr/local/bin/certspotter
COPY --from=upstream /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENV HOME=/data
WORKDIR /data
VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/certspotter"]
CMD ["-watchlist", "/data/watchlist"]
USER 65532:65532
