# Immutable upstream input; Dependabot updates the tag and digest in PRs.
FROM registry-1.docker.io/kanidm/server:1.11.2@sha256:e45f00bd354c1fc1c06a4be484b4e87b094c431e78280f1d19e911815e63efb5
#!DisableOBSContainerSupport
COPY --chmod=0644 hardened-malloc.so /usr/local/lib/libhardened_malloc.so
COPY --chmod=0755 allocator-check /usr/local/bin/allocator-check
COPY --chmod=0644 hardened-malloc.LICENSE /usr/share/licenses/hardened_malloc/LICENSE
ENV LD_PRELOAD=/usr/local/lib/libhardened_malloc.so
COPY --chmod=0644 ld.so.preload /etc/ld.so.preload
USER 65532:65532
VOLUME ["/data"]
