# Immutable upstream input; Dependabot updates the tag and digest in PRs.
FROM registry-1.docker.io/certbot/certbot:v5.8.0@sha256:f70ad0adbb7e117f0fe42a63c553f28ea451edabc0148757b6efcd9735acaa20
#!DisableOBSContainerSupport
USER 0:0
RUN find / -xdev -type f \( -perm -4000 -o -perm -2000 \) -exec chmod a-s '{}' +
RUN mkdir -p /etc/letsencrypt /var/lib/letsencrypt /var/log/letsencrypt && chown -R 65532:65532 /etc/letsencrypt /var/lib/letsencrypt /var/log/letsencrypt
ENV HOME=/var/lib/letsencrypt PYTHONMALLOC=malloc
VOLUME ["/etc/letsencrypt", "/var/lib/letsencrypt", "/var/log/letsencrypt"]
COPY --chmod=0644 hardened-malloc.so /usr/local/lib/libhardened_malloc.so
COPY --chmod=0755 allocator-check /usr/local/bin/allocator-check
COPY --chmod=0644 hardened-malloc.LICENSE /usr/share/licenses/hardened_malloc/LICENSE
ENV LD_PRELOAD=/usr/local/lib/libhardened_malloc.so
USER 65532:65532
