# Immutable upstream input; Dependabot updates the tag and digest in PRs.
FROM registry-1.docker.io/library/nginx:1.31.0-alpine@sha256:2f07d83bf561b506400dc183b1b2003803e39efbd22451f848adaba14d28c7c7
#!DisableOBSContainerSupport
USER 0:0
RUN find / -xdev -type f \( -perm -4000 -o -perm -2000 \) -exec chmod a-s '{}' +
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
EXPOSE 8080
COPY --chmod=0644 hardened-malloc.so /usr/local/lib/libhardened_malloc.so
COPY --chmod=0755 allocator-check /usr/local/bin/allocator-check
COPY --chmod=0644 hardened-malloc.LICENSE /usr/share/licenses/hardened_malloc/LICENSE
ENV LD_PRELOAD=/usr/local/lib/libhardened_malloc.so
USER 101:101
