# Immutable upstream input; Dependabot updates the tag and digest in PRs.
FROM ghcr.io/matter-js/python-matter-server:8.1.2@sha256:6827e352011e2d8c2bde771e446fcf72acc49150ef66bad978816bac1762aad3
#!DisableOBSContainerSupport
USER 0:0
RUN find / -xdev -type f \( -perm -4000 -o -perm -2000 \) -exec chmod a-s '{}' +
RUN rm -f /usr/bin/ping /bin/ping && mkdir -p /data && chown 65532:65532 /data
ENV HOME=/data PYTHONMALLOC=malloc
VOLUME ["/data"]
COPY --chmod=0644 hardened-malloc.so /usr/local/lib/libhardened_malloc.so
COPY --chmod=0755 allocator-check /usr/local/bin/allocator-check
COPY --chmod=0644 hardened-malloc.LICENSE /usr/share/licenses/hardened_malloc/LICENSE
ENV LD_PRELOAD=/usr/local/lib/libhardened_malloc.so
COPY --chmod=0644 ld.so.preload /etc/ld.so.preload
USER 65532:65532
