#!RemoteAsset: https://github.com/kanidm/kanidm/archive/refs/tags/v1.11.2.tar.gz sha256:a8ed31203e5f8c036b9cb261c85ddac19291bc6ca16981495495cd9621c56529 upstream.tar.gz
FROM registry-1.docker.io/library/alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4 AS builder
RUN apk add cargo clang build-base cmake pkgconf openssl-dev
WORKDIR /src
COPY upstream.tar.gz vendor.tar.gz /tmp/
RUN tar -xzf /tmp/upstream.tar.gz -C /src --strip-components=1 && tar -xzf /tmp/vendor.tar.gz -C /src \
    && mkdir -p .cargo && printf '[source.crates-io]\nreplace-with = "vendored-sources"\n[source.vendored-sources]\ndirectory = "vendor"\n' > .cargo/config.toml
# Dynamic musl linking allows hardened_malloc to interpose Rust's system allocator.
ENV RUSTFLAGS="-C target-feature=-crt-static" CARGO_NET_OFFLINE=true CARGO_BUILD_JOBS=2
RUN apk add freeradius-dev talloc-dev
RUN cp rlm_kanidm/module/include/automask.h rlm_kanidm/module/include/connection.h rlm_kanidm/module/include/log.h \
      rlm_kanidm/module/include/xlat.h rlm_kanidm/module/include/tmpl.h rlm_kanidm/module/include/clients.h \
      rlm_kanidm/module/include/process.h rlm_kanidm/module/include/listen.h /usr/include/freeradius/
RUN cargo build --offline --locked --release -p rlm_kanidm --features extern-freeradius-module --lib \
    && cargo build --offline --locked --release -p kanidm_radiusd --bin kanidm_radiusd \
    && strip target/release/librlm_kanidm.so target/release/kanidm_radiusd
FROM registry-1.docker.io/library/alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4
RUN apk add ca-certificates freeradius freeradius-eap freeradius-utils openssl libgcc
COPY --from=builder /src/target/release/librlm_kanidm.so /usr/lib/freeradius/rlm_kanidm.so
COPY --from=builder /src/target/release/kanidm_radiusd /usr/local/bin/kanidm_radiusd
COPY --from=builder /src/rlm_kanidm/container/mods-available/ /etc/raddb/mods-available/
COPY --from=builder /src/rlm_kanidm/container/sites-available/ /etc/raddb/sites-available/
RUN ln -sf ../mods-available/kanidm_rust /etc/raddb/mods-enabled/kanidm \
    && ln -sf ../sites-available/check-eap-tls /etc/raddb/sites-enabled/check-eap-tls \
    && rm -f /etc/raddb/mods-enabled/passwd /etc/raddb/mods-enabled/totp /etc/raddb/mods-available/sql \
    && mkdir -p /data /etc/raddb/certs /run/radiusd /var/log/radius \
    && chown -R 497:496 /data /etc/raddb /run/radiusd /var/log/radius
ENV KANIDM_CONFIG_FILE=/data/radius.toml HOME=/data
VOLUME ["/data"]
EXPOSE 1812/udp 1813/udp
ENTRYPOINT ["/usr/local/bin/kanidm_radiusd"]
RUN find / -xdev -type f \( -perm -4000 -o -perm -2000 \) -exec chmod a-s '{}' +
COPY --chmod=0644 hardened-malloc.so /usr/local/lib/libhardened_malloc.so
COPY --chmod=0755 allocator-check /usr/local/bin/allocator-check
COPY --chmod=0644 hardened-malloc.LICENSE /usr/share/licenses/hardened_malloc/LICENSE
ENV LD_PRELOAD=/usr/local/lib/libhardened_malloc.so
USER 497:496
